# Generated by Django 5.1.8 on 2025-04-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
