# Generated by Django 5.1.8 on 2025-04-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchase_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='complete',
        ),
    ]
