# Generated by Django 5.1.8 on 2025-04-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_purchase_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
