# Generated by Django 5.1.8 on 2025-04-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='product',
            new_name='product_name',
        ),
    ]
