# Generated by Django 5.1.8 on 2025-04-28 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_rename_product_purchase_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='product_name',
            new_name='product',
        ),
    ]
