# Generated by Django 5.1.8 on 2025-04-29 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_rename_product_name_purchase_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
    ]
