# Generated by Django 5.1.8 on 2025-04-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_purchase_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='product_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
