# Generated by Django 5.1.8 on 2025-04-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_purchase_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='handle',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
