# Generated by Django 5.1.8 on 2025-04-30 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_purchase_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='handle',
        ),
    ]
