# Generated by Django 5.1.8 on 2025-05-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_remove_purchase_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='product_number',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
