# Generated by Django 5.1.8 on 2025-05-03 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_purchase_product_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product_number',
        ),
    ]
