# Generated by Django 5.1.8 on 2025-05-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_remove_purchase_product_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='handle',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
