# Generated by Django 5.1.8 on 2025-05-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0015_purchase_stripe_checkout_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
