# Generated by Django 5.1.8 on 2025-06-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0018_alter_purchase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_invoice',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
