# Generated by Django 5.1.8 on 2025-06-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0019_purchase_purchase_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='handle',
        ),
    ]
