# Generated by Django 5.1.8 on 2025-06-14 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0020_remove_purchase_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
