# Generated by Django 5.1.8 on 2025-06-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0021_alter_purchase_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product_name',
            field=models.CharField(help_text='This Name must match the product name Exactly!', max_length=120, null=True),
        ),
    ]
