# Generated by Django 5.1.8 on 2026-01-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformpage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
