# Generated by Django 5.1.8 on 2025-09-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindex',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
