# Generated by Django 5.1.8 on 2025-09-29 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindex_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindex',
            name='description',
        ),
    ]
