# Generated by Django 5.1.8 on 2025-09-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogindex_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
