# Generated by Django 5.1.8 on 2025-09-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogdetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='description',
            field=models.CharField(blank=True, help_text='210 Characters, about 35 words.', max_length=210),
        ),
    ]
