# Generated by Django 5.1.8 on 2025-10-05 18:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blogdetail_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('code', 4)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 3: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 4: ('wagtail.blocks.StructBlock', [[('language', 2), ('code', 3)]], {'label': 'Code'})}, null=True),
        ),
    ]
