# Generated by Django 5.1.8 on 2025-10-14 23:58

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogdetail_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('code', 4), ('page', 5), ('doc', 6), ('rich_text', 7)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('scss', 'SCSS'), ('json', 'JSON'), ('bash', 'Bash/Shell'), ('diff', 'diff'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 3: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 4: ('wagtail.blocks.StructBlock', [[('language', 2), ('code', 3)]], {'label': 'Code'}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'document-link', 'image', 'ol', 'ul', 'blockquote', 'code']})}, null=True),
        ),
    ]
