# Generated by Django 5.1.8 on 2025-10-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_author_first_name_remove_author_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
