# Generated by Django 5.1.8 on 2025-10-15 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_author_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
