# Generated by Django 5.1.8 on 2025-10-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UserName', max_length=60)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
