# Generated by Django 5.1.8 on 2025-10-15 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='full_name',
        ),
    ]
