# Generated by Django 5.1.8 on 2025-10-15 10:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_author_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('code', 4), ('page', 5), ('doc', 6), ('author', 7), ('rich_text', 8)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('scss', 'SCSS'), ('json', 'JSON'), ('bash', 'Bash/Shell'), ('diff', 'diff'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 3: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 4: ('wagtail.blocks.StructBlock', [[('language', 2), ('code', 3)]], {'label': 'Code'}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blog.Author',), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'document-link', 'image', 'ol', 'ul', 'blockquote', 'code']})}, null=True),
        ),
    ]
