# Generated by Django 5.1.8 on 2025-10-18 20:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('divider', 1), ('image', 2), ('code', 5), ('page', 6), ('doc', 7), ('author', 8), ('rich_text', 9), ('faq', 13), ('call_to_action_1', 16), ('carousel', 18)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'This is a content divider with extra information.'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('scss', 'SCSS'), ('json', 'JSON'), ('bash', 'Bash/Shell'), ('diff', 'diff'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 4: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 5: ('wagtail.blocks.StructBlock', [[('language', 3), ('code', 4)]], {'label': 'Code'}), 6: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blog.Author',), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'document-link', 'image', 'ol', 'ul', 'blockquote', 'code']}), 10: ('wagtail.blocks.CharBlock', (), {}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'document-link']}), 12: ('wagtail.blocks.StructBlock', [[('question', 10), ('answer', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'FAQ'}), 14: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'rquired': True}), 15: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('text', 14), ('page', 6), ('button_text', 15)]], {'label': 'CTA #1'}), 17: ('wagtail.blocks.StructBlock', [[('text', 0), ('author', 0)]], {}), 18: ('wagtail.blocks.StreamBlock', [[('image', 2), ('quotation', 17)]], {})}, null=True),
        ),
    ]
