# Generated by Django 5.1.8 on 2025-10-18 23:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('divider', 0), ('image', 1), ('code', 4), ('text', 5), ('page', 6), ('doc', 7), ('author', 8), ('rich_text', 9), ('faq', 10), ('call_to_action', 14), ('carousel', 17)], blank=True, block_lookup={0: ('app_blocks.app_blocks.InfoBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('scss', 'SCSS'), ('json', 'JSON'), ('bash', 'Bash/Shell'), ('diff', 'diff'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 3: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 4: ('wagtail.blocks.StructBlock', [[('language', 2), ('code', 3)]], {'label': 'Code'}), 5: ('app_blocks.app_blocks.TextBlock', (), {}), 6: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blog.Author',), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'document-link', 'image', 'ol', 'ul', 'blockquote', 'code']}), 10: ('app_blocks.app_blocks.FAQListBlock', (), {}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'rquired': True}), 12: ('wagtail.blocks.PageChooserBlock', (), {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('text', 11), ('page', 12), ('button_text', 13)]], {}), 15: ('wagtail.blocks.TextBlock', (), {}), 16: ('wagtail.blocks.StructBlock', [[('text', 15), ('author', 15)]], {}), 17: ('wagtail.blocks.StreamBlock', [[('image', 1), ('quotation', 16)]], {})}, null=True),
        ),
    ]
