# Generated by Django 5.1.8 on 2025-11-01 23:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('article_section', 2), ('divider', 3), ('image', 4), ('code', 7), ('text', 8), ('page', 9), ('doc', 10), ('faq', 11), ('call_to_action', 15), ('carousel', 19), ('rich_text', 20)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'document-link', 'image', 'ol', 'ul', 'blockquote', 'code'], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('header', 0), ('content', 1)]], {}), 3: ('app_blocks.app_blocks.InfoBlock', (), {}), 4: ('app_blocks.app_blocks.ImageBlock', (), {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('scss', 'SCSS'), ('json', 'JSON'), ('bash', 'Bash/Shell'), ('diff', 'diff'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 6: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 7: ('wagtail.blocks.StructBlock', [[('language', 5), ('code', 6)]], {'group': 'Coding', 'label': 'Code'}), 8: ('app_blocks.app_blocks.TextBlock', (), {}), 9: ('wagtail.blocks.PageChooserBlock', (), {'group': 'Standalone Blocks', 'required': False}), 10: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'group': 'Standalone Blocks'}), 11: ('app_blocks.app_blocks.FAQListBlock', (), {}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 13: ('wagtail.blocks.PageChooserBlock', (), {}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('text', 12), ('page', 13), ('button_text', 14)]], {}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 17: ('wagtail.blocks.TextBlock', (), {}), 18: ('wagtail.blocks.StructBlock', [[('text', 17), ('author', 17)]], {}), 19: ('wagtail.blocks.StreamBlock', [[('image', 16), ('quotation', 18)]], {}), 20: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'document-link', 'image', 'ol', 'ul', 'blockquote', 'code'], 'group': 'Coding'})}, null=True),
        ),
    ]
