# Generated by Django 5.1.8 on 2025-11-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_blogauthororderable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='subtitle',
        ),
    ]
