# Generated by Django 5.1.8 on 2025-07-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_heropagecarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
