# Generated by Django 5.1.8 on 2025-07-04 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_sub_title'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sub_title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='heropagecarousel',
            name='slider_sub_title',
            field=models.CharField(blank=True, help_text='Slider Sub Title Text Goes Here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heropagecarousel',
            name='slider_title',
            field=models.CharField(blank=True, help_text='Slider Title Text Goes Here', max_length=100, null=True),
        ),
    ]
