# Generated by Django 5.1.8 on 2025-09-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sitepage_alter_heropagecarousel_slider_sub_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SitePage',
        ),
    ]
