# Generated by Django 5.1.8 on 2025-09-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_sitepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroPageCarousel',
        ),
    ]
