# Generated by Django 5.1.8 on 2026-01-18 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blocks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomEmailForm',
        ),
    ]
