# Generated by Django 5.1.8 on 2026-01-21 01:44

import django.core.serializers.json
import django.db.models.deletion
import wagtail.fields
import wagtail_flexible_forms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_blocks', '0002_delete_customemailform'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('form_fields', wagtail.fields.StreamField([('sf_singleline', 5), ('sf_multiline', 7), ('sf_checkboxes', 10), ('sf_radios', 13), ('sf_dropdown', 13), ('sf_checkbox', 15), ('sf_date', 17), ('sf_time', 19), ('sf_datetime', 21), ('sf_image', 22), ('sf_file', 22), ('text', 23), ('image', 24)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Label'}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Help text', 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'label': 'Required', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('email', 'Email'), ('url', 'URL')], 'label': 'Format', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Default value', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2), ('format', 3), ('default_value', 4)]], {'group': 'Fields'}), 6: ('wagtail.blocks.TextBlock', (), {'label': 'Default value', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2), ('default_value', 6)]], {'group': 'Fields'}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Checkbox'}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2), ('checkboxes', 9)]], {'group': 'Fields'}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Choice'}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2), ('choices', 12)]], {'group': 'Fields'}), 14: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 15: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('default_value', 14)]], {'group': 'Fields'}), 16: ('wagtail.blocks.DateBlock', (), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2), ('default_value', 16)]], {'group': 'Fields'}), 18: ('wagtail.blocks.TimeBlock', (), {'required': False}), 19: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2), ('default_value', 18)]], {'group': 'Fields'}), 20: ('wagtail.blocks.DateTimeBlock', (), {'required': False}), 21: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2), ('default_value', 20)]], {'group': 'Fields'}), 22: ('wagtail.blocks.StructBlock', [[('field_label', 0), ('help_text', 1), ('required', 2)]], {'group': 'Fields'}), 23: ('wagtail.blocks.RichTextBlock', (), {'group': 'Content'}), 24: ('app_blocks.app_blocks.ImageBlock', (), {'group': 'Content'})})),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_flexible_forms.models.StreamFormMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='MySubmissionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('created', 'Created'), ('changed', 'Changed'), ('deleted', 'Deleted')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission_id', models.TextField()),
                ('data', models.TextField()),
                ('summary', models.TextField()),
                ('submission_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MySessionFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='submit time')),
                ('session_key', models.CharField(default=None, max_length=40, null=True)),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='last modification')),
                ('status', models.CharField(choices=[('incomplete', 'Not submitted'), ('complete', 'Complete'), ('reviewed', 'Under consideration'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='incomplete', max_length=10)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'form submission',
                'verbose_name_plural': 'form submissions',
                'abstract': False,
                'unique_together': {('page', 'session_key'), ('page', 'user')},
            },
        ),
    ]
