# Generated by Django 5.1.8 on 2026-01-21 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blocks', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysubmissionrevision',
            name='submission_ct',
        ),
        migrations.RemoveField(
            model_name='streamformpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='MySessionFormSubmission',
        ),
        migrations.DeleteModel(
            name='MySubmissionRevision',
        ),
        migrations.DeleteModel(
            name='StreamFormPage',
        ),
    ]
