# Generated by Django 5.1.8 on 2025-04-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productlistingpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
