# Generated by Django 5.1.8 on 2025-04-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
