# Generated by Django 5.1.8 on 2025-04-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_product_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_attachment',
        ),
    ]
