# Generated by Django 5.1.8 on 2025-04-26 21:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_product_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_attachment',
            field=wagtail.fields.StreamField([('document', 0)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})}, null=True),
        ),
    ]
