# Generated by Django 5.1.8 on 2025-04-27 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_active_product_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_free',
        ),
    ]
