# Generated by Django 5.1.8 on 2025-04-27 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_documentcollection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentCollection',
        ),
    ]
