# Generated by Django 5.1.8 on 2025-06-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_customdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='handle',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(help_text='The Purchase Product Name must match this name Exactly!', max_length=120),
        ),
    ]
